name: Dispatch

on: repository_dispatch

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo apt update --quiet
          sudo apt install --quiet --yes jq
          echo ${{ github.event.client_payload }} | jq "."
