name: Dispatch

on: repository_dispatch

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: sergeysova/jq-action@v2
        with:
          cmd: echo '${{ toJSON(github.event.client_payload) }}' | jq "."
          multiline: true
